version: '3.9'

services:
  webapi:
    image: ${CONTAINER_REGISTRY-}aspnet-api-template:${IMAGE_TAG:-dev}
    container_name: webapi
    build:
      context: ../src
      dockerfile: Dockerfile
      args:
        - CONFIGURATION=Debug
    restart: 'no'
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - ASPNETCORE_DETAILEDERRORS=${ASPNETCORE_DETAILEDERRORS:-1}
    ports:
      - ${ASPNETCORE_HTTP_PORT:-8080}
